### ISSUE TITLE
README: missing database server information

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/dio-service#11]
Following the instructions, running `npm start` results in:

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13
Express server listening on port 3000 in development mode
Unable to connect to the database: { SequelizeHostNotFoundError: getaddrinfo ENOTFOUND undefined undefined:3306
    at Utils.Promise.tap.then.catch.err (/Users/yongbakos/projects/cs496/dio-service/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:143:19)
    at tryCatcher (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/yongbakos/projects/cs496/dio-service/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  name: 'SequelizeHostNotFoundError',
  parent:
   { Error: getaddrinfo ENOTFOUND undefined undefined:3306
       at errnoException (dns.js:53:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'undefined',
     host: 'undefined',
     port: 3306,
     fatal: true },
  original:
   { Error: getaddrinfo ENOTFOUND undefined undefined:3306
       at errnoException (dns.js:53:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'undefined',
     host: 'undefined',
     port: 3306,
     fatal: true } }

**Comment by ybakos** [comment]
After running **sequelize init**,

**node_modules/.bin/sequelize db:migrate**

Sequelize CLI [Node: 8.5.0, CLI: 3.0.0, ORM: 4.20.1]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "config/config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13

ERROR: connect ECONNREFUSED 127.0.0.1:3306

**Comment by JWTappert** [comment]
@ybakos this error should now be fixed by the config.json file being present I think
